# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version: '2'

run:
  allow-parallel-runners: true

linters:
  default: none
  enable:
    # Enabled
    - asasalint
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - customlint
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - fatcontext
    - gocheckcompilerdirectives
    - goprintffuncname
    - govet
    - grouper
    - inamedparam
    - ineffassign
    - intrange
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nolintlint
    - paralleltest
    - perfsprint
    - predeclared
    - reassign
    - testableexamples
    - tparallel
    - unconvert
    - usestdlibvars
    - usetesting

    # Need to add headers
    # - goheader

    # Check
    # - exhaustive
    # - gocritic
    # - gosec
    # - revive
    # - staticcheck
    # - testifylint
    # - unparam
    # - unused

  settings:
    custom:
      customlint:
        type: module

  exclusions:
    presets:
      - comments
      - std-error-handling

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
